In [1]:
import pandas as pd

## clean all data


### Clean campaign_interactions

In [2]:
# read data file

campaign_interactions = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\campaign_interactions.csv")

In [3]:
#clean function
def clean_campaign_interactions(csv_file):

    # change coulmns name
    csv_file = csv_file.rename(columns = {"converted" : "campaign_converted"})

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # trim index of the columns
    for strip in ["interaction_type" , "campaign_id" , "interaction_id" , "campaign_converted"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["campaign_converted" , "interaction_type"]:
        csv_file[lower] = csv_file[lower].str.lower()

    #  change str type to category
    for i in ['campaign_id', 'interaction_type', 'campaign_converted' , "interaction_id"] :
        csv_file[i] = csv_file[i].astype('category')

    # remove nan value
    csv_file.dropna(subset="campaign_id" , inplace= True)

    # change str type to date
    csv_file['interaction_date'] = pd.to_datetime(
    csv_file['interaction_date'],
    format='mixed',
    errors='coerce'
    )

    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()

    return csv_file

In [4]:
# show first 5 rows 

campaign_interactions.head()

,interaction_id,user_id,campaign_id,interaction_date,interaction_type,converted
0,INT-0000001,737,CMP-0022,15/10/2025,Email Open,No
1,INT-0000002,1196,CMP-0011,14 Dec 2025,Trial Signup,No
2,INT-0000003,120,CMP-0011,09/29/2025,IMPRESSION,No
3,INT-0000004,755,CMP-0010,02/07/2025,email open,no
4,INT-0000005,1252,CMP-0009,"Mar 02, 2025",Trial Signup,No

In [5]:
# show number of rows and columns

campaign_interactions.shape

(15100, 6)

In [6]:
# show data info

campaign_interactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 15100 entries, 0 to 15099
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   interaction_id    15100 non-null  str
 1   user_id           15100 non-null  int64
 2   campaign_id       14884 non-null  str
 3   interaction_date  15100 non-null  str
 4   interaction_type  15100 non-null  str
 5   converted         15100 non-null  str
dtypes: int64(1), str(5)
memory usage: 707.9 KB

In [7]:
# show number of dublicate rows in the data

campaign_interactions.duplicated().sum()

np.int64(100)

In [8]:
# show nun values number in data

campaign_interactions.isnull().sum()

interaction_id        0
user_id               0
campaign_id         216
interaction_date      0
interaction_type      0
converted             0
dtype: int64

In [9]:
# run clean function on the data

campaign_interactions = clean_campaign_interactions(campaign_interactions)

In [10]:
# show first 5 rows after cleaning

campaign_interactions.head()

,interaction_id,user_id,campaign_id,interaction_date,interaction_type,campaign_converted
0,INT-0000001,737,CMP-0022,2025-10-15,email open,no
1,INT-0000002,1196,CMP-0011,2025-12-14,trial signup,no
2,INT-0000003,120,CMP-0011,2025-09-29,impression,no
3,INT-0000004,755,CMP-0010,2025-02-07,email open,no
4,INT-0000005,1252,CMP-0009,2025-03-02,trial signup,no

In [11]:
# show data info after cleaning data

campaign_interactions.info()

<class 'pandas.DataFrame'>
Index: 14785 entries, 0 to 14999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   interaction_id      14785 non-null  category
 1   user_id             14785 non-null  int64
 2   campaign_id         14785 non-null  category
 3   interaction_date    14785 non-null  datetime64[us]
 4   interaction_type    14785 non-null  category
 5   campaign_converted  14785 non-null  category
dtypes: category(4), datetime64[us](1), int64(1)
memory usage: 536.4 KB

In [12]:
# show number of rows and columns after cleaning

campaign_interactions.shape

(14785, 6)

In [13]:
# show nun values number in data after cleaning
 
campaign_interactions.isnull().sum()

interaction_id        0
user_id               0
campaign_id           0
interaction_date      0
interaction_type      0
campaign_converted    0
dtype: int64

In [14]:
# show number of dublicate rows in the data after cleaning

campaign_interactions.duplicated().sum()

np.int64(0)


### Clean marketing_campaigns

In [15]:
# read data file

marketing_campaigns = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\marketing_campaigns.csv")

In [16]:
#clean function
def clean_marketing_campaigns(csv_file):

    # rename some columns
    csv_file.rename(columns={"channel" : "campaign_channel" , "budget" : "campaign_budget" }  , inplace= True)

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # clean budget column
    csv_file["campaign_budget"] = csv_file["campaign_budget"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["campaign_budget"] = pd.to_numeric(csv_file["campaign_budget"] , errors="coerce")

    # change str type to date
    csv_file['start_date'] = pd.to_datetime(csv_file['start_date'], format='mixed', errors='coerce')

    # remove start_date column
    csv_file.drop(columns= "start_date" , inplace= True)

    # trim index of the columns
    for strip in ["campaign_id" ,  "campaign_name" , "campaign_channel" , "campaign_type"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["campaign_name" , "campaign_channel" , "campaign_type"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["campaign_id" ,  "campaign_name" , "campaign_channel" , "campaign_type"] :
        csv_file[i] = csv_file[i].astype('category')    

    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()  

    return csv_file

In [17]:
# show first 5 rows 

marketing_campaigns.head()

,campaign_id,campaign_name,channel,campaign_type,start_date,budget
0,CMP-0001,Synergistic logistical structure,Facebook,Acquisition,16-12-2025,"25,610.55"
1,CMP-0002,Cross-platform zero administration policy,Referral,Acquisition,26/04/2025,"$24,239.16"
2,CMP-0003,Organic clear-thinking product,linkedin,Upsell,2025-09-05,"$8,895.16"
3,CMP-0004,Advanced encompassing application,email,Acquisition,2025-09-10,$9115
4,CMP-0005,Re-contextualized systematic data-warehouse,LinkedIn,Brand Awareness,29-05-2025,"15,765.50 USD"

In [18]:
# show number of rows and columns

marketing_campaigns.shape

(32, 6)

In [19]:
# show data info

marketing_campaigns.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    32 non-null     str
 1   campaign_name  32 non-null     str
 2   channel        32 non-null     str
 3   campaign_type  32 non-null     str
 4   start_date     32 non-null     str
 5   budget         32 non-null     str
dtypes: str(6)
memory usage: 1.6 KB

In [20]:
# show number of dublicate rows in the data

marketing_campaigns.duplicated().sum()

np.int64(2)

In [21]:
# show nun values number in data

marketing_campaigns.isnull().sum()

campaign_id      0
campaign_name    0
channel          0
campaign_type    0
start_date       0
budget           0
dtype: int64

In [22]:
# run clean function on the data

marketing_campaigns = clean_marketing_campaigns(marketing_campaigns)

In [23]:
# show first 5 rows after cleaning

marketing_campaigns.head()

,campaign_id,campaign_name,campaign_channel,campaign_type,campaign_budget
0,CMP-0001,synergistic logistical structure,facebook,acquisition,25610.55
1,CMP-0002,cross-platform zero administration policy,referral,acquisition,24239.16
2,CMP-0003,organic clear-thinking product,linkedin,upsell,8895.16
3,CMP-0004,advanced encompassing application,email,acquisition,9115.00
4,CMP-0005,re-contextualized systematic data-warehouse,linkedin,brand awareness,15765.50

In [24]:
# show data info after cleaning data

marketing_campaigns.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       30 non-null     category
 1   campaign_name     30 non-null     category
 2   campaign_channel  30 non-null     category
 3   campaign_type     30 non-null     category
 4   campaign_budget   30 non-null     float64
dtypes: category(4), float64(1)
memory usage: 1.0 KB

In [25]:
# show number of rows and columns after cleaning

marketing_campaigns.shape

(30, 5)

In [26]:
# show nun values number in data after cleaning
 
marketing_campaigns.isnull().sum()

campaign_id         0
campaign_name       0
campaign_channel    0
campaign_type       0
campaign_budget     0
dtype: int64

In [27]:
# show number of dublicate rows in the data after cleaning

marketing_campaigns.duplicated().sum()

np.int64(0)


### Clean subscriptions

In [28]:
# read data file
subscriptions = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\subscriptions.csv")

In [29]:
#clean function
def clean_subscriptions(csv_file):

    # rename some columns
    csv_file.rename(columns={"plan" : "sub_plan" , "billing_cycle" : "sub_billing_cycle", "monthly_fee" : "sub_monthly_fee", "discount" : "sub_discount", "status" : "sub_status" } , inplace= True)

    # remove start_date and end_date columns
    csv_file = csv_file.drop(columns= ["start_date" , "end_date"])

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # clean monthly_fee column
    csv_file["sub_monthly_fee"] = csv_file["sub_monthly_fee"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["sub_monthly_fee"] = pd.to_numeric(csv_file["sub_monthly_fee"] , errors="coerce")

    # fill nall values in monthly_fee
    csv_file["sub_monthly_fee"] = csv_file["sub_monthly_fee"].fillna(csv_file["sub_monthly_fee"].median())

    # clean discount column
    csv_file["sub_discount"] = csv_file["sub_discount"].str.replace(" ","").str.replace("%" , "")
    csv_file["sub_discount"] = (csv_file["sub_discount"].fillna(0).astype("float")) / 100

    # trim index of the columns
    for strip in ["subscription_id", "sub_plan", "sub_billing_cycle", "sub_status"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["sub_plan" , "sub_billing_cycle" , "sub_status"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["sub_plan" , "sub_billing_cycle" , "sub_status" , "subscription_id"] :
        csv_file[i] = csv_file[i].astype('category')
    
    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()
    

    return csv_file

In [30]:
# show first 5 rows 

subscriptions.head()

,subscription_id,user_id,plan,billing_cycle,start_date,end_date,monthly_fee,discount,status
0,SUB-000001,1183,Business,Annual,06/02/2025,22-08-2025,$280.82,10%,PAUSED
1,SUB-000002,107,Starter,Monthly,10/29/2025,NaN,54.55,15%,ACTIVE
2,SUB-000003,326,professional,Annual,"May 07, 2025",NaN,USD 160.27,5%,Active
3,SUB-000004,35,professional,Annual,2025-12-29,NaN,USD 162.93,20%,Active
4,SUB-000005,1495,Business,monthly,"Sep 10, 2025",NaN,USD 290.18,0 %,active

In [31]:
# show number of rows and columns

subscriptions.shape

(7075, 9)

In [32]:
# show data info

subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 7075 entries, 0 to 7074
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subscription_id  7075 non-null   str
 1   user_id          7075 non-null   int64
 2   plan             7075 non-null   str
 3   billing_cycle    7075 non-null   str
 4   start_date       7075 non-null   str
 5   end_date         2451 non-null   str
 6   monthly_fee      7073 non-null   str
 7   discount         6793 non-null   str
 8   status           7075 non-null   str
dtypes: int64(1), str(8)
memory usage: 497.6 KB

In [33]:
# show number of dublicate rows in the data

subscriptions.duplicated().sum()

np.int64(69)

In [34]:
#show duplicates rows content 
dupl_before = subscriptions[subscriptions.duplicated(keep=False)].sort_values("user_id")
dupl_before

,subscription_id,user_id,plan,billing_cycle,start_date,end_date,monthly_fee,discount,status
3820,SUB-003821,11,BUSINESS,ANNUAL,24-12-2025,NaN,335.23 USD,15%,Active
7058,SUB-003821,11,BUSINESS,ANNUAL,24-12-2025,NaN,335.23 USD,15%,Active
7059,SUB-003326,26,starter,ANNUAL,12/12/2025,09 Jun 2026,$48.99,5%,Paused
3325,SUB-003326,26,starter,ANNUAL,12/12/2025,09 Jun 2026,$48.99,5%,Paused
4755,SUB-004756,45,STARTER,Quarterly,12/09/2025,NaN,$49.65,20%,Active
...,...,...,...,...,...,...,...,...,...
7055,SUB-000762,1432,Enterprise,MONTHLY,12-03-2025,01/07/2026,807.40 USD,20.0%,PAUSED
5553,SUB-005554,1435,Starter,Quarterly,2025-09-06,NaN,USD 53.82,0%,Active
7015,SUB-005554,1435,Starter,Quarterly,2025-09-06,NaN,USD 53.82,0%,Active
536,SUB-000537,1447,Business,monthly,"Dec 19, 2025",NaN,331.27,5%,Active
7072,SUB-000537,1447,Business,monthly,"Dec 19, 2025",NaN,331.27,5%,Active

In [35]:
# show nun values number in data

subscriptions.isnull().sum()

subscription_id       0
user_id               0
plan                  0
billing_cycle         0
start_date            0
end_date           4624
monthly_fee           2
discount            282
status                0
dtype: int64

In [36]:
# run clean function on the data

subscriptions = clean_subscriptions(subscriptions)

In [37]:
# show first 5 rows after cleaning

subscriptions.head()

,subscription_id,user_id,sub_plan,sub_billing_cycle,sub_monthly_fee,sub_discount,sub_status
0,SUB-000001,1183,business,annual,280.82,0.10,paused
1,SUB-000002,107,starter,monthly,54.55,0.15,active
2,SUB-000003,326,professional,annual,160.27,0.05,active
3,SUB-000004,35,professional,annual,162.93,0.20,active
4,SUB-000005,1495,business,monthly,290.18,0.00,active

In [38]:
# show data info after cleaning data

subscriptions.info()

<class 'pandas.DataFrame'>
Index: 7006 entries, 0 to 7068
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    7006 non-null   category
 1   user_id            7006 non-null   int64
 2   sub_plan           7006 non-null   category
 3   sub_billing_cycle  7006 non-null   category
 4   sub_monthly_fee    7006 non-null   float64
 5   sub_discount       7006 non-null   float64
 6   sub_status         7006 non-null   category
dtypes: category(4), float64(2), int64(1)
memory usage: 307.9 KB

In [39]:
# show number of rows and columns after cleaning
subscriptions.shape

(7006, 7)

In [40]:
# show nun values number in data after cleaning
 
subscriptions.isnull().sum()

subscription_id      0
user_id              0
sub_plan             0
sub_billing_cycle    0
sub_monthly_fee      0
sub_discount         0
sub_status           0
dtype: int64

In [41]:
# show number of dublicate rows in the data after cleaning

subscriptions.duplicated().sum()

np.int64(0)


### Clean support_tickets

In [42]:
# read data file

support_tickets = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\support_tickets.csv")

In [43]:
#clean function
def clean_support_tickets(csv_file):

    # rename some columns
    csv_file.rename(columns={"category" : "tic_category", "priority" : "tic_priority", "resolution_hours" : "tic_resolution_hours", "satisfaction" : "cus_satisfaction" } , inplace= True)

    # remove start_date and end_date columns
    csv_file = csv_file.drop(columns= ["opened_date"])

    # fill null values of satisfaction column
    csv_file["cus_satisfaction"] = csv_file["cus_satisfaction"].fillna(csv_file["cus_satisfaction"].mean())

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # trim index of the columns
    for strip in ["ticket_id", "tic_category", "tic_priority", "ticket_status"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["tic_category", "tic_priority", "ticket_status"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["ticket_id", "tic_category", "tic_priority", "ticket_status"] :
        csv_file[i] = csv_file[i].astype('category')
    
    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()

    

    return csv_file

In [44]:
# show first 5 rows 

support_tickets.head()

,ticket_id,user_id,opened_date,category,priority,resolution_hours,satisfaction,ticket_status
0,TCK-000001,355,28/09/2025,Security,CRITICAL,8.0,1.0,open
1,TCK-000002,440,04 Feb 2025,Account,LOW,14.4,5.0,resolved
2,TCK-000003,196,12/16/2025,Performance,LOW,10.5,3.0,OPEN
3,TCK-000004,1420,2025-03-03,Account,Low,15.8,5.0,Open
4,TCK-000005,910,29-10-2025,FEATURE REQUEST,HIGH,14.1,5.0,Closed

In [45]:
# show number of rows and columns

support_tickets.shape

(6075, 8)

In [46]:
# show data info

support_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 6075 entries, 0 to 6074
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ticket_id         6075 non-null   str
 1   user_id           6075 non-null   int64
 2   opened_date       6075 non-null   str
 3   category          6075 non-null   str
 4   priority          6075 non-null   str
 5   resolution_hours  6075 non-null   float64
 6   satisfaction      5086 non-null   float64
 7   ticket_status     6075 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 379.8 KB

In [47]:
# show number of dublicate rows in the data

support_tickets.duplicated().sum()

np.int64(75)

In [48]:
#show duplicates rows content 
dupl_before = support_tickets[support_tickets.duplicated(keep=False)].sort_values("user_id")
dupl_before

,ticket_id,user_id,opened_date,category,priority,resolution_hours,satisfaction,ticket_status
4985,TCK-004986,1,01-08-2025,Performance,low,6.3,5.0,Pending
6072,TCK-004986,1,01-08-2025,Performance,low,6.3,5.0,Pending
6024,TCK-002658,30,08/08/2025,performance,Low,8.5,NaN,Open
2657,TCK-002658,30,08/08/2025,performance,Low,8.5,NaN,Open
6062,TCK-000011,36,"Aug 16, 2025",Feature Request,Low,6.4,NaN,Pending
...,...,...,...,...,...,...,...,...
6025,TCK-004533,1452,13-07-2025,account,Critical,6.9,2.0,Resolved
3225,TCK-003226,1458,16-12-2025,Feature Request,Medium,9.9,1.0,OPEN
6044,TCK-003226,1458,16-12-2025,Feature Request,Medium,9.9,1.0,OPEN
1683,TCK-001684,1473,25/09/2025,Technical,Low,8.4,1.0,OPEN
6057,TCK-001684,1473,25/09/2025,Technical,Low,8.4,1.0,OPEN

In [49]:
# show nun values number in data

support_tickets.isnull().sum()

ticket_id             0
user_id               0
opened_date           0
category              0
priority              0
resolution_hours      0
satisfaction        989
ticket_status         0
dtype: int64

In [50]:
# run clean function on the data

support_tickets = clean_support_tickets(support_tickets)

In [51]:
# show first 5 rows after cleaning

support_tickets.head()

,ticket_id,user_id,tic_category,tic_priority,tic_resolution_hours,cus_satisfaction,ticket_status
0,TCK-000001,355,security,critical,8.0,1.0,open
1,TCK-000002,440,account,low,14.4,5.0,resolved
2,TCK-000003,196,performance,low,10.5,3.0,open
3,TCK-000004,1420,account,low,15.8,5.0,open
4,TCK-000005,910,feature request,high,14.1,5.0,closed

In [52]:
# show data info after cleaning data

support_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ticket_id             6000 non-null   category
 1   user_id               6000 non-null   int64
 2   tic_category          6000 non-null   category
 3   tic_priority          6000 non-null   category
 4   tic_resolution_hours  6000 non-null   float64
 5   cus_satisfaction      6000 non-null   float64
 6   ticket_status         6000 non-null   category
dtypes: category(4), float64(2), int64(1)
memory usage: 217.0 KB

In [53]:
# show number of rows and columns after cleaning
support_tickets.shape

(6000, 7)

In [54]:
# show nun values number in data after cleaning
 
support_tickets.isnull().sum()

ticket_id               0
user_id                 0
tic_category            0
tic_priority            0
tic_resolution_hours    0
cus_satisfaction        0
ticket_status           0
dtype: int64

In [55]:
# show number of dublicate rows in the data after cleaning

support_tickets.duplicated().sum()

np.int64(0)


### Clean transactions_q1

In [56]:
# read data file

transactions_q1 = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\transactions_q1.csv")

In [57]:
#clean function
def clean_transactions_q1(csv_file):

    # change str type to date
    csv_file['transaction_date'] = pd.to_datetime(csv_file['transaction_date'], format='mixed', errors='coerce')

    # clean monthly_fee column
    csv_file["amount"] = csv_file["amount"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["amount"] = pd.to_numeric(csv_file["amount"] , errors="coerce")

    # replace - by _ in transaction_type column
    csv_file["transaction_type"] = csv_file["transaction_type"].str.replace("-" , "_")    

    # drop nall values in amount column
    csv_file.dropna(subset="amount" , inplace= True)

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # trim index of the columns
    for strip in ["transaction_id", "payment_method", "transaction_type"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["payment_method", "transaction_type"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["transaction_id", "payment_method", "transaction_type"] :
        csv_file[i] = csv_file[i].astype('category')
    
    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()

    # rename some columns
    csv_file = csv_file.rename(columns={"amount" : "trans_amount", "payment_method" : "trans_payment_method"})

    return csv_file

In [58]:
# show first 5 rows 

transactions_q1.head()

,transaction_id,user_id,transaction_date,amount,payment_method,transaction_type
0,Q1-TX-000001,1295,2025-03-28,-251.05,Credit Card,REFUND
1,Q1-TX-000002,779,19 Feb 2025,278.74,CREDIT CARD,Subscription
2,Q1-TX-000003,748,23 Mar 2025,366.75 USD,PayPal,Subscription
3,Q1-TX-000004,1434,14-01-2025,USD 333.67,PayPal,SUBSCRIPTION
4,Q1-TX-000005,158,2025-02-15,134.27,PayPal,upgrade

In [59]:
transactions_q1.describe()

             user_id
count    3025.000000
mean     6686.017190
std     72892.175112
min         1.000000
25%       357.000000
50%       742.000000
75%      1123.000000
max    900019.000000

In [60]:
# show number of rows and columns

transactions_q1.shape

(3025, 6)

In [61]:
# show data info

transactions_q1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    3025 non-null   str
 1   user_id           3025 non-null   int64
 2   transaction_date  3025 non-null   str
 3   amount            2963 non-null   str
 4   payment_method    3025 non-null   str
 5   transaction_type  3025 non-null   str
dtypes: int64(1), str(5)
memory usage: 141.9 KB

In [62]:
# show number of dublicate rows in the data

transactions_q1.duplicated().sum()

np.int64(25)

In [63]:
#show duplicates rows content 
dupl_before = transactions_q1[transactions_q1.duplicated(keep=False)].sort_values("user_id")
dupl_before.head(10)

,transaction_id,user_id,transaction_date,amount,payment_method,transaction_type
1280,Q1-TX-001281,107,05-03-2025,633.01,DEBIT CARD,ADD-ON
3023,Q1-TX-001281,107,05-03-2025,633.01,DEBIT CARD,ADD-ON
3021,Q1-TX-001308,240,06 Jan 2025,-214.84,Credit Card,Refund
1307,Q1-TX-001308,240,06 Jan 2025,-214.84,Credit Card,Refund
1569,Q1-TX-001570,294,23/02/2025,$351.59,Debit Card,Subscription
3015,Q1-TX-001570,294,23/02/2025,$351.59,Debit Card,Subscription
3008,Q1-TX-002583,319,19 Feb 2025,138.29 USD,Credit Card,Add-on
2582,Q1-TX-002583,319,19 Feb 2025,138.29 USD,Credit Card,Add-on
1725,Q1-TX-001726,389,"Jan 29, 2025",$280.11,bank transfer,add-on
3006,Q1-TX-001726,389,"Jan 29, 2025",$280.11,bank transfer,add-on

In [64]:
# show nun values number in data

transactions_q1.isnull().sum()

transaction_id       0
user_id              0
transaction_date     0
amount              62
payment_method       0
transaction_type     0
dtype: int64

In [65]:
# run clean function on the data

transactions_q1 = clean_transactions_q1(transactions_q1)

In [66]:
# show first 5 rows after cleaning

transactions_q1.head()

,transaction_id,user_id,transaction_date,trans_amount,trans_payment_method,transaction_type
0,Q1-TX-000001,1295,2025-03-28,-251.05,credit card,refund
1,Q1-TX-000002,779,2025-02-19,278.74,credit card,subscription
2,Q1-TX-000003,748,2025-03-23,366.75,paypal,subscription
3,Q1-TX-000004,1434,2025-01-14,333.67,paypal,subscription
4,Q1-TX-000005,158,2025-02-15,134.27,paypal,upgrade

In [67]:
# show data info after cleaning data

transactions_q1.info()

<class 'pandas.DataFrame'>
Index: 2939 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        2939 non-null   category
 1   user_id               2939 non-null   int64
 2   transaction_date      2939 non-null   datetime64[us]
 3   trans_amount          2939 non-null   float64
 4   trans_payment_method  2939 non-null   category
 5   transaction_type      2939 non-null   category
dtypes: category(3), datetime64[us](1), float64(1), int64(1)
memory usage: 126.3 KB

In [68]:
# show number of rows and columns after cleaning
transactions_q1.shape

(2939, 6)

In [69]:
# show nun values number in data after cleaning
 
transactions_q1.isnull().sum()

transaction_id          0
user_id                 0
transaction_date        0
trans_amount            0
trans_payment_method    0
transaction_type        0
dtype: int64

In [70]:
transactions_q1[transactions_q1["trans_amount"].isnull()]

Empty DataFrame
Columns: [transaction_id, user_id, transaction_date, trans_amount, trans_payment_method, transaction_type]
Index: []

In [71]:
# show number of dublicate rows in the data after cleaning

transactions_q1.duplicated().sum()

np.int64(0)


### Clean transactions_q2

In [72]:
# read data file

transactions_q2 = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\transactions_q2.csv")

In [73]:
#clean function
def clean_transactions_q2(csv_file):

    # change str type to date
    csv_file['transaction_date'] = pd.to_datetime(csv_file['transaction_date'], format='mixed', errors='coerce')

    # clean monthly_fee column
    csv_file["transaction_amount"] = csv_file["transaction_amount"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["transaction_amount"] = pd.to_numeric(csv_file["transaction_amount"] , errors="coerce")

    # replace - by _ in transaction_type column
    csv_file["transaction_type"] = csv_file["transaction_type"].str.replace("-" , "_")

    # drop nall values in amount column
    csv_file.dropna(subset="transaction_amount" , inplace= True)

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # trim index of the columns
    for strip in ["transaction_id" , "payment_method" , "transaction_type"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["payment_method" , "transaction_type"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["transaction_id" , "payment_method" , "transaction_type"] :
        csv_file[i] = csv_file[i].astype('category')

    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()

    # rename some columns
    csv_file = csv_file.rename(columns={"payment_method" : "trans_payment_method", "transaction_amount" : "trans_amount"})

    return csv_file

In [74]:
# show first 5 rows 

transactions_q2.head()

,transaction_id,user_id,transaction_date,transaction_amount,payment_method,transaction_type
0,Q2-TX-000001,628,28/04/2025,163.69,BANK TRANSFER,Add-on
1,Q2-TX-000002,1452,20 Apr 2025,$-161,Bank Transfer,Refund
2,Q2-TX-000003,1119,04/05/2025,-99.48 USD,Debit Card,Refund
3,Q2-TX-000004,130,26-04-2025,$176,credit card,SUBSCRIPTION
4,Q2-TX-000005,883,11-06-2025,42.00,Credit Card,SUBSCRIPTION

In [75]:
# show number of rows and columns
transactions_q2.shape

(3025, 6)

In [76]:
# show data info

transactions_q2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      3025 non-null   str
 1   user_id             3025 non-null   int64
 2   transaction_date    3025 non-null   str
 3   transaction_amount  2959 non-null   str
 4   payment_method      3025 non-null   str
 5   transaction_type    3025 non-null   str
dtypes: int64(1), str(5)
memory usage: 141.9 KB

In [77]:
# show number of dublicate rows in the data

transactions_q2.duplicated().sum()

np.int64(25)

In [78]:
#show duplicates rows content 
dupl_before = transactions_q2[transactions_q2.duplicated(keep=False)].sort_values("user_id")
dupl_before.head(10)

,transaction_id,user_id,transaction_date,transaction_amount,payment_method,transaction_type
1269,Q2-TX-001270,28,05/08/2025,$285,debit card,ADD-ON
3001,Q2-TX-001270,28,05/08/2025,$285,debit card,ADD-ON
2930,Q2-TX-002931,32,"Jun 15, 2025",$-227,Debit Card,refund
3012,Q2-TX-002931,32,"Jun 15, 2025",$-227,Debit Card,refund
3023,Q2-TX-000168,111,03/05/2025,-464.24,Credit Card,refund
167,Q2-TX-000168,111,03/05/2025,-464.24,Credit Card,refund
1273,Q2-TX-001274,140,22 May 2025,-212.03 USD,CREDIT CARD,Refund
3019,Q2-TX-001274,140,22 May 2025,-212.03 USD,CREDIT CARD,Refund
566,Q2-TX-000567,153,2025-05-20,378.80 USD,Credit Card,Upgrade
3004,Q2-TX-000567,153,2025-05-20,378.80 USD,Credit Card,Upgrade

In [79]:
# show nun values number in data

transactions_q2.isnull().sum()

transaction_id         0
user_id                0
transaction_date       0
transaction_amount    66
payment_method         0
transaction_type       0
dtype: int64

In [80]:
# run clean function on the data

transactions_q2 = clean_transactions_q2(transactions_q2)

In [81]:
# show first 5 rows after cleaning

transactions_q2.head()

,transaction_id,user_id,transaction_date,trans_amount,trans_payment_method,transaction_type
0,Q2-TX-000001,628,2025-04-28,163.69,bank transfer,add_on
1,Q2-TX-000002,1452,2025-04-20,-161.00,bank transfer,refund
2,Q2-TX-000003,1119,2025-04-05,-99.48,debit card,refund
3,Q2-TX-000004,130,2025-04-26,176.00,credit card,subscription
4,Q2-TX-000005,883,2025-11-06,42.00,credit card,subscription

In [82]:
# show data info after cleaning data

transactions_q2.info()

<class 'pandas.DataFrame'>
Index: 2936 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        2936 non-null   category
 1   user_id               2936 non-null   int64
 2   transaction_date      2936 non-null   datetime64[us]
 3   trans_amount          2936 non-null   float64
 4   trans_payment_method  2936 non-null   category
 5   transaction_type      2936 non-null   category
dtypes: category(3), datetime64[us](1), float64(1), int64(1)
memory usage: 126.2 KB

In [83]:
# show number of rows and columns after cleaning
transactions_q2.shape

(2936, 6)

In [84]:
# show nun values number in data after cleaning
 
transactions_q2.isnull().sum()

transaction_id          0
user_id                 0
transaction_date        0
trans_amount            0
trans_payment_method    0
transaction_type        0
dtype: int64

In [85]:
transactions_q2[transactions_q2["trans_amount"].isnull()]

Empty DataFrame
Columns: [transaction_id, user_id, transaction_date, trans_amount, trans_payment_method, transaction_type]
Index: []

In [86]:
# show number of dublicate rows in the data after cleaning

transactions_q2.duplicated().sum()

np.int64(0)


### Clean transactions_q3

In [87]:
# read data file

transactions_q3 = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\transactions_q3.csv")

In [88]:
#clean function
def clean_transactions_q3(csv_file):

    # remove source_system coulmn
    csv_file = csv_file.drop(columns = "source_system")

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()
    
    # change str type to date
    csv_file['transaction_date'] = pd.to_datetime(csv_file['transaction_date'], format='mixed', errors='coerce')

    # clean monthly_fee column
    csv_file["amount"] = csv_file["amount"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["amount"] = pd.to_numeric(csv_file["amount"] , errors="coerce")

    # replace - by _ in transaction_type column
    csv_file["transaction_type"] = csv_file["transaction_type"].str.replace("-" , "_")

    # drop nall values in amount column
    csv_file.dropna(subset="amount" , inplace= True)

    # trim index of the columns
    for strip in ["transaction_id" , "payment_type" , "transaction_type"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["payment_type" , "transaction_type"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["transaction_id" , "payment_type" , "transaction_type"] :
        csv_file[i] = csv_file[i].astype('category')

    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()

    # rename amount column an payment_type column
    csv_file = csv_file.rename(columns={"amount" : "trans_amount" , "payment_type" : "trans_payment_method"})

    return csv_file

In [89]:
# show first 5 rows 

transactions_q3.head()

,transaction_id,user_id,transaction_date,amount,payment_type,transaction_type,source_system
0,Q3-TX-000001,918,2025-07-16,USD 209.38,Bank Transfer,Subscription,Legacy Billing
1,Q3-TX-000002,338,09/25/2025,212.29,Credit Card,add-on,Legacy Billing
2,Q3-TX-000003,1039,03-08-2025,USD 341.01,Credit Card,ADD-ON,Legacy Billing
3,Q3-TX-000004,361,2025-08-25,665.58 USD,Credit Card,Add-on,Legacy Billing
4,Q3-TX-000005,1098,09/23/2025,USD -152.49,debit card,refund,Legacy Billing

In [90]:
# show number of rows and columns

transactions_q3.shape

(3025, 7)

In [91]:
# show data info

transactions_q3.info()

<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    3025 non-null   str
 1   user_id           3025 non-null   int64
 2   transaction_date  3025 non-null   str
 3   amount            2971 non-null   str
 4   payment_type      3025 non-null   str
 5   transaction_type  3025 non-null   str
 6   source_system     3025 non-null   str
dtypes: int64(1), str(6)
memory usage: 165.6 KB

In [92]:
# show number of dublicate rows in the data

transactions_q3.duplicated().sum()

np.int64(25)

In [93]:
#show duplicates rows content 
dupl_before = transactions_q3[transactions_q3.duplicated(keep=False)].sort_values("user_id")
dupl_before.head(10)

,transaction_id,user_id,transaction_date,amount,payment_type,transaction_type,source_system
483,Q3-TX-000484,4,"Aug 25, 2025",276.32 USD,BANK TRANSFER,Subscription,Legacy Billing
3009,Q3-TX-000484,4,"Aug 25, 2025",276.32 USD,BANK TRANSFER,Subscription,Legacy Billing
3021,Q3-TX-000584,83,28 Sep 2025,103.37,BANK TRANSFER,Add-on,Legacy Billing
583,Q3-TX-000584,83,28 Sep 2025,103.37,BANK TRANSFER,Add-on,Legacy Billing
2788,Q3-TX-002789,124,12-07-2025,110.29 USD,Bank Transfer,Upgrade,Legacy Billing
3024,Q3-TX-002789,124,12-07-2025,110.29 USD,Bank Transfer,Upgrade,Legacy Billing
3007,Q3-TX-000138,179,"Aug 02, 2025",610.90 USD,Debit Card,Subscription,Legacy Billing
137,Q3-TX-000138,179,"Aug 02, 2025",610.90 USD,Debit Card,Subscription,Legacy Billing
3002,Q3-TX-001643,251,09/21/2025,198.68,debit card,UPGRADE,Legacy Billing
1642,Q3-TX-001643,251,09/21/2025,198.68,debit card,UPGRADE,Legacy Billing

In [94]:
# show nun values number in data

transactions_q3.isnull().sum()

transaction_id       0
user_id              0
transaction_date     0
amount              54
payment_type         0
transaction_type     0
source_system        0
dtype: int64

In [95]:
# run clean function on the data

transactions_q3 = clean_transactions_q3(transactions_q3)

In [96]:
# show first 5 rows after cleaning

transactions_q3.head()

,transaction_id,user_id,transaction_date,trans_amount,trans_payment_method,transaction_type
0,Q3-TX-000001,918,2025-07-16,209.38,bank transfer,subscription
1,Q3-TX-000002,338,2025-09-25,212.29,credit card,add_on
2,Q3-TX-000003,1039,2025-03-08,341.01,credit card,add_on
3,Q3-TX-000004,361,2025-08-25,665.58,credit card,add_on
4,Q3-TX-000005,1098,2025-09-23,-152.49,debit card,refund

In [97]:
# show data info after cleaning data

transactions_q3.info()

<class 'pandas.DataFrame'>
Index: 2946 entries, 0 to 2998
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        2946 non-null   category
 1   user_id               2946 non-null   int64
 2   transaction_date      2946 non-null   datetime64[us]
 3   trans_amount          2946 non-null   float64
 4   trans_payment_method  2946 non-null   category
 5   transaction_type      2946 non-null   category
dtypes: category(3), datetime64[us](1), float64(1), int64(1)
memory usage: 126.6 KB

In [98]:
# show number of rows and columns after cleaning
transactions_q3.shape

(2946, 6)

In [99]:
# show nun values number in data after cleaning
 
transactions_q3.isnull().sum()

transaction_id          0
user_id                 0
transaction_date        0
trans_amount            0
trans_payment_method    0
transaction_type        0
dtype: int64

In [100]:
transactions_q3[transactions_q3["trans_amount"].isnull()]

Empty DataFrame
Columns: [transaction_id, user_id, transaction_date, trans_amount, trans_payment_method, transaction_type]
Index: []

In [101]:
# show number of dublicate rows in the data after cleaning

transactions_q3.duplicated().sum()

np.int64(0)


### Clean transactions_q4

In [102]:
# read data file

transactions_q4 = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\transactions_q4.csv")

In [103]:
#clean function
def clean_transactions_q4(csv_file):

    # remove source_system coulmn
    csv_file = csv_file.drop(columns = "currency")

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # change str type to date
    csv_file['transaction_date'] = pd.to_datetime(csv_file['transaction_date'], format='mixed', errors='coerce')

    # clean monthly_fee column
    csv_file["transaction_amount"] = csv_file["transaction_amount"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["transaction_amount"] = pd.to_numeric(csv_file["transaction_amount"] , errors="coerce")

    # replace - by _ in transaction_type column
    csv_file["transaction_type"] = csv_file["transaction_type"].str.replace("-" , "_")

    # drop nall values in amount column
    csv_file.dropna(subset="transaction_amount" , inplace= True)

    # trim index of the columns
    for strip in ["transaction_id" , "payment_type" , "transaction_type"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["payment_type" , "transaction_type"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["transaction_id" , "payment_type" , "transaction_type"] :
        csv_file[i] = csv_file[i].astype('category')

    # remove dublicate rows
    csv_file = csv_file.drop_duplicates()

    # rename amount column an payment_type column
    csv_file = csv_file.rename(columns={"payment_type" : "trans_payment_method", "transaction_amount" : "trans_amount"})

    return csv_file

In [104]:
# show first 5 rows 

transactions_q4.head()

,transaction_id,user_id,transaction_date,transaction_amount,payment_type,transaction_type,currency
0,Q4-TX-000001,1165,"Nov 18, 2025",$273.37,Credit Card,Subscription,US Dollar
1,Q4-TX-000002,443,11/12/2025,126.41,debit card,Upgrade,usd
2,Q4-TX-000003,340,03-11-2025,USD 260.82,bank transfer,Upgrade,usd
3,Q4-TX-000004,1116,2025-11-24,368.91,paypal,add-on,USD
4,Q4-TX-000005,726,17/10/2025,302.15 USD,Bank Transfer,SUBSCRIPTION,USD

In [105]:
# show number of rows and columns

transactions_q4.shape

(3025, 7)

In [106]:
# show data info

transactions_q4.info()

<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      3025 non-null   str
 1   user_id             3025 non-null   int64
 2   transaction_date    3025 non-null   str
 3   transaction_amount  2948 non-null   str
 4   payment_type        3025 non-null   str
 5   transaction_type    3025 non-null   str
 6   currency            3025 non-null   str
dtypes: int64(1), str(6)
memory usage: 165.6 KB

In [107]:
# show number of dublicate rows in the data

transactions_q4.duplicated().sum()

np.int64(25)

In [108]:
#show duplicates rows content 
dupl_before = transactions_q4[transactions_q4.duplicated(keep=False)].sort_values("user_id")
dupl_before.head(10)

,transaction_id,user_id,transaction_date,transaction_amount,payment_type,transaction_type,currency
3004,Q4-TX-002623,4,"Nov 04, 2025",$-145.04,Debit Card,Refund,usd
2622,Q4-TX-002623,4,"Nov 04, 2025",$-145.04,Debit Card,Refund,usd
350,Q4-TX-000351,22,"Nov 03, 2025",244.50,Bank Transfer,Upgrade,USD
3010,Q4-TX-000351,22,"Nov 03, 2025",244.50,Bank Transfer,Upgrade,USD
3002,Q4-TX-002067,28,"Dec 29, 2025",$117,PayPal,ADD-ON,US Dollar
2066,Q4-TX-002067,28,"Dec 29, 2025",$117,PayPal,ADD-ON,US Dollar
3013,Q4-TX-002553,29,17/10/2025,USD -232.25,Debit Card,refund,US Dollar
2552,Q4-TX-002553,29,17/10/2025,USD -232.25,Debit Card,refund,US Dollar
332,Q4-TX-000333,59,04 Dec 2025,414.02,Credit Card,Upgrade,usd
3014,Q4-TX-000333,59,04 Dec 2025,414.02,Credit Card,Upgrade,usd

In [109]:
# show nun values number in data

transactions_q4.isnull().sum()

transaction_id         0
user_id                0
transaction_date       0
transaction_amount    77
payment_type           0
transaction_type       0
currency               0
dtype: int64

In [110]:
# run clean function on the data

transactions_q4 = clean_transactions_q4(transactions_q4)

In [111]:
# show first 5 rows after cleaning

transactions_q4.head()

,transaction_id,user_id,transaction_date,trans_amount,trans_payment_method,transaction_type
0,Q4-TX-000001,1165,2025-11-18,273.37,credit card,subscription
1,Q4-TX-000002,443,2025-11-12,126.41,debit card,upgrade
2,Q4-TX-000003,340,2025-03-11,260.82,bank transfer,upgrade
3,Q4-TX-000004,1116,2025-11-24,368.91,paypal,add_on
4,Q4-TX-000005,726,2025-10-17,302.15,bank transfer,subscription

In [112]:
# show data info after cleaning data

transactions_q4.info()

<class 'pandas.DataFrame'>
Index: 2923 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        2923 non-null   category
 1   user_id               2923 non-null   int64
 2   transaction_date      2923 non-null   datetime64[us]
 3   trans_amount          2923 non-null   float64
 4   trans_payment_method  2923 non-null   category
 5   transaction_type      2923 non-null   category
dtypes: category(3), datetime64[us](1), float64(1), int64(1)
memory usage: 125.8 KB

In [113]:
# show number of rows and columns after cleaning
transactions_q4.shape

(2923, 6)

In [114]:
# show nun values number in data after cleaning
 
transactions_q4.isnull().sum()

transaction_id          0
user_id                 0
transaction_date        0
trans_amount            0
trans_payment_method    0
transaction_type        0
dtype: int64

In [115]:
transactions_q4[transactions_q4["trans_amount"].isnull()]

Empty DataFrame
Columns: [transaction_id, user_id, transaction_date, trans_amount, trans_payment_method, transaction_type]
Index: []

In [116]:
# show number of dublicate rows in the data after cleaning

transactions_q4.duplicated().sum()

np.int64(0)


### Clean Customers

In [117]:
# read data file

customers = pd.read_csv(r"G:\courses\DEPI\TEQ\week5\Customer 360 project\Week 05\customers.csv")

In [118]:
#clean function
def clean_customers(csv_file):

    # change str type to date
    for date_col in ["birth_date" , "registration_date" , "last_login_date"]:
        csv_file[date_col] = pd.to_datetime(csv_file[date_col], format='mixed', errors='coerce')

    # remove some coulmns
    csv_file = csv_file.drop(columns = ["email_address", "phone_number" , "address"])

    # remove dublicate rows by user id
    csv_file.drop_duplicates(subset= "user_id" , inplace=True)

    # change columns name to lower casa and trim text
    csv_file.columns = csv_file.columns.str.strip().str.lower()

    # clean annual_revenue column and fill nan values
    csv_file["annual_revenue"] = csv_file["annual_revenue"].str.replace("USD" , "" , regex=False).str.replace("$" , "" , regex=False).str.replace("," , "" , regex=False).str.strip()
    csv_file["annual_revenue"] = pd.to_numeric(csv_file["annual_revenue"] , errors="coerce")

    # fill nan values in "annual_revenue" coulmn
    csv_file["annual_revenue"] = csv_file["annual_revenue"].fillna(csv_file["annual_revenue"].median())
    
    # fill nan values in company_name coulmn
    csv_file["company_name"] = csv_file["company_name"].fillna("unknown")

    # fill nan values in last_login_date coulmn
    csv_file["last_login_date"] = csv_file["last_login_date"].ffill()
    
    # trim index of the columns
    for strip in ["full_name", "job_title", "company_name", "city", "country", "account_status"]:
        csv_file[strip] = csv_file[strip].str.strip()

    # change text to lower case in index of the columns
    for lower in ["full_name", "job_title", "company_name", "city", "country", "account_status"]:
        csv_file[lower] = csv_file[lower].str.lower()

    # change str type to category
    for i in ["full_name", "job_title", "company_name", "city", "country", "account_status"] :
        csv_file[i] = csv_file[i].astype('category')

    return csv_file

In [119]:
# show first 5 rows 
customers.head()

,user_id,full_name,job_title,company_name,email_address,phone_number,address,city,country,birth_date,registration_date,last_login_date,account_status,annual_revenue
0,1,Sarah Riggs,Financial Analyst,Garcia Inc.,amy50@example.com,531-371-3900x532,"335 Kristina Ranch\nWest Micheleberg, DC 71308",Paris,germany,1967-11-28,2024-07-17,03/25/2025,inactive,464027.88
1,2,Katie Wilson,Data Scientist,Thompson LLC,andersonmichael@example.org,001-350-324-0268,"917 Sonia Cape Suite 700\nBoonechester, TX 14651",Toronto,NETHERLANDS,1979-08-25,2025-05-14,2025-05-23,Active,297513.53
2,3,Laura Gray,COO,Browning Systems,lammarc@example.org,624-999-8569,"18367 Robert Views Suite 661\nRonaldview, MN 2...",Singapore,Spain,1989-04-12,2024-02-12,"Dec 09, 2025",active,515752.34
3,4,Joseph Lawson,IT Specialist,Wells Inc.,deckerchristopher@example.org,001-252-680-9885x1656,"98327 Melanie Keys Suite 149\nPort Roy, OH 81991",Oslo,Italy,1985-09-09,2023-11-23,"Nov 07, 2025",Active,951810.18
4,5,Jeffrey Fowler,Research Scientist,Day Holdings,lynchdiane@example.net,302-444-5502x296,"83667 Moore Inlet\nKimberlyshire, PA 11636",Berlin,DENMARK,1998-11-29,29-07-2023,2023-11-01,Inactive,278199.19

In [120]:
# show number of rows and columns
customers.shape

(1575, 14)

In [121]:
# show data info
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1575 entries, 0 to 1574
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1575 non-null   int64
 1   full_name          1575 non-null   str
 2   job_title          1575 non-null   str
 3   company_name       1507 non-null   str
 4   email_address      1548 non-null   str
 5   phone_number       1535 non-null   str
 6   address            1575 non-null   str
 7   city               1575 non-null   str
 8   country            1575 non-null   str
 9   birth_date         1575 non-null   str
 10  registration_date  1575 non-null   str
 11  last_login_date    1499 non-null   str
 12  account_status     1575 non-null   str
 13  annual_revenue     1535 non-null   str
dtypes: int64(1), str(13)
memory usage: 172.4 KB

In [122]:
# show number of dublicate rows in the data

customers.duplicated(subset="user_id").sum()

np.int64(75)

In [123]:
#show duplicates rows content 
dupl_before = customers[customers.duplicated(subset="user_id", keep=False)]
dupl_before.isna().sum()

user_id              0
full_name            0
job_title            0
company_name         7
email_address        2
phone_number         3
address              0
city                 0
country              0
birth_date           0
registration_date    0
last_login_date      4
account_status       0
annual_revenue       4
dtype: int64

In [124]:
# show nun values number in data
customers.isnull().sum()

user_id               0
full_name             0
job_title             0
company_name         68
email_address        27
phone_number         40
address               0
city                  0
country               0
birth_date            0
registration_date     0
last_login_date      76
account_status        0
annual_revenue       40
dtype: int64

In [125]:
# run clean function on the data
customers = clean_customers(customers)

In [126]:
# show first 5 rows after cleaning
customers.head()

,user_id,full_name,job_title,company_name,city,country,birth_date,registration_date,last_login_date,account_status,annual_revenue
0,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88
1,2,katie wilson,data scientist,thompson llc,toronto,netherlands,1979-08-25,2025-05-14,2025-05-23,active,297513.53
2,3,laura gray,coo,browning systems,singapore,spain,1989-04-12,2024-02-12,2025-12-09,active,515752.34
3,4,joseph lawson,it specialist,wells inc.,oslo,italy,1985-09-09,2023-11-23,2025-11-07,active,951810.18
4,5,jeffrey fowler,research scientist,day holdings,berlin,denmark,1998-11-29,2023-07-29,2023-11-01,inactive,278199.19

In [127]:
# show data info after cleaning data
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1500 non-null   int64
 1   full_name          1500 non-null   category
 2   job_title          1500 non-null   category
 3   company_name       1500 non-null   category
 4   city               1500 non-null   category
 5   country            1500 non-null   category
 6   birth_date         1500 non-null   datetime64[us]
 7   registration_date  1500 non-null   datetime64[us]
 8   last_login_date    1500 non-null   datetime64[us]
 9   account_status     1500 non-null   category
 10  annual_revenue     1500 non-null   float64
dtypes: category(6), datetime64[us](3), float64(1), int64(1)
memory usage: 92.3 KB

In [128]:
# show number of rows and columns after cleaning
transactions_q4.shape

(2923, 6)

In [129]:
# show nun values number in data after cleaning
 
customers.isnull().sum()

user_id              0
full_name            0
job_title            0
company_name         0
city                 0
country              0
birth_date           0
registration_date    0
last_login_date      0
account_status       0
annual_revenue       0
dtype: int64

In [130]:
# show number of dublicate rows in the data after cleaning

customers.duplicated().isna().sum()

np.int64(0)

## test -- merge and concat data

In [131]:
# Concat all transactions
all_trans = pd.concat([transactions_q1, transactions_q2, transactions_q3, transactions_q4], ignore_index=True)
all_trans

,transaction_id,user_id,transaction_date,trans_amount,trans_payment_method,transaction_type
0,Q1-TX-000001,1295,2025-03-28,-251.05,credit card,refund
1,Q1-TX-000002,779,2025-02-19,278.74,credit card,subscription
2,Q1-TX-000003,748,2025-03-23,366.75,paypal,subscription
3,Q1-TX-000004,1434,2025-01-14,333.67,paypal,subscription
4,Q1-TX-000005,158,2025-02-15,134.27,paypal,upgrade
...,...,...,...,...,...,...
11739,Q4-TX-002995,767,2025-11-06,815.00,debit card,add_on
11740,Q4-TX-002996,809,2025-11-10,380.22,paypal,upgrade
11741,Q4-TX-002998,800,2025-12-16,280.54,credit card,add_on
11742,Q4-TX-002999,931,2025-11-25,459.80,bank transfer,upgrade
11743,Q4-TX-003000,936,2025-10-27,-202.18,credit card,refund

### merge campaign tables and customer table

In [132]:
# process of merge
customer_camp_interaction = pd.merge(campaign_interactions , marketing_campaigns , on="campaign_id")
customer_camp_interaction = pd.merge(customers , customer_camp_interaction , on="user_id")
customer_camp_interaction

,user_id,full_name,job_title,company_name,city,country,birth_date,registration_date,last_login_date,account_status,annual_revenue,interaction_id,campaign_id,interaction_date,interaction_type,campaign_converted,campaign_name,campaign_channel,campaign_type,campaign_budget
0,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,INT-0000823,CMP-0018,2025-04-07,demo request,no,polarized motivating encoding,linkedin,brand awareness,40782.02
1,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,INT-0002556,CMP-0010,2025-05-17,website visit,no,configurable systemic support,webinar,retention,32244.60
2,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,INT-0002642,CMP-0026,2025-05-27,demo request,yes,re-contextualized motivating protocol,webinar,retention,33667.00
3,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,INT-0003044,CMP-0011,2025-09-11,email open,yes,virtual logistical definition,linkedin,retention,7236.65
4,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,INT-0003964,CMP-0022,2025-08-26,impression,no,proactive regional workforce,email,retention,42955.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14735,1500,matthew bowen,it specialist,mcbride technologies,madrid,india,1969-07-13,2024-04-16,2025-02-21,inactive,496217.13,INT-0009948,CMP-0019,2025-05-06,impression,yes,re-engineered user-facing algorithm,linkedin,retention,14663.59
14736,1500,matthew bowen,it specialist,mcbride technologies,madrid,india,1969-07-13,2024-04-16,2025-02-21,inactive,496217.13,INT-0010612,CMP-0024,2025-05-25,website visit,no,right-sized asynchronous application,referral,upsell,7767.49
14737,1500,matthew bowen,it specialist,mcbride technologies,madrid,india,1969-07-13,2024-04-16,2025-02-21,inactive,496217.13,INT-0010623,CMP-0001,2025-06-19,impression,yes,synergistic logistical structure,facebook,acquisition,25610.55
14738,1500,matthew bowen,it specialist,mcbride technologies,madrid,india,1969-07-13,2024-04-16,2025-02-21,inactive,496217.13,INT-0010753,CMP-0028,2025-02-05,trial signup,no,diverse even-keeled frame,email,upsell,49020.45
14739,1500,matthew bowen,it specialist,mcbride technologies,madrid,india,1969-07-13,2024-04-16,2025-02-21,inactive,496217.13,INT-0013477,CMP-0021,2025-10-27,impression,yes,configurable composite hierarchy,facebook,brand awareness,33834.17

In [141]:
customer_camp_interaction.groupby("full_name")["interaction_id"].count().reset_index().sort_values(by="full_name" , ascending= True).head(5)

        full_name  interaction_id
0      aaron bray              11
1    aaron duarte              10
2  aaron espinoza               8
3   aaron francis              11
4      aaron king              10

In [ ]:
# view nan values
customer_camp_interaction.isnull().sum()

user_id               0
full_name             0
job_title             0
company_name          0
city                  0
country               0
birth_date            0
registration_date     0
last_login_date       0
account_status        0
annual_revenue        0
interaction_id        0
campaign_id           0
interaction_date      0
interaction_type      0
campaign_converted    0
campaign_name         0
campaign_channel      0
campaign_type         0
campaign_budget       0
dtype: int64

In [ ]:
# view data info
customer_camp_interaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 14740 entries, 0 to 14739
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             14740 non-null  int64
 1   full_name           14740 non-null  category
 2   job_title           14740 non-null  category
 3   company_name        14740 non-null  category
 4   city                14740 non-null  category
 5   country             14740 non-null  category
 6   birth_date          14740 non-null  datetime64[us]
 7   registration_date   14740 non-null  datetime64[us]
 8   last_login_date     14740 non-null  datetime64[us]
 9   account_status      14740 non-null  category
 10  annual_revenue      14740 non-null  float64
 11  interaction_id      14740 non-null  category
 12  campaign_id         14740 non-null  str
 13  interaction_date    14740 non-null  datetime64[us]
 14  interaction_type    14740 non-null  category
 15  campaign_converted  14740 non-null  category
 16  campaign_name       14740 non-null  category
 17  campaign_channel    14740 non-null  category
 18  campaign_type       14740 non-null  category
 19  campaign_budget     14740 non-null  float64
dtypes: category(12), datetime64[us](4), float64(2), int64(1), str(1)
memory usage: 1.2 MB

### merge subscriptions table and customer table

In [ ]:
# process of merge
customer_subscriptions = pd.merge(customers, subscriptions, on="user_id")
customer_subscriptions

,user_id,full_name,job_title,company_name,city,country,birth_date,registration_date,last_login_date,account_status,annual_revenue,subscription_id,sub_plan,sub_billing_cycle,sub_monthly_fee,sub_discount,sub_status
0,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,SUB-004384,professional,annual,140.11,0.10,active
1,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,SUB-005669,professional,quarterly,137.65,0.10,active
2,1,sarah riggs,financial analyst,garcia inc.,paris,germany,1967-11-28,2024-07-17,2025-03-25,inactive,464027.88,SUB-006480,enterprise,monthly,736.45,0.15,active
3,2,katie wilson,data scientist,thompson llc,toronto,netherlands,1979-08-25,2025-05-14,2025-05-23,active,297513.53,SUB-000896,business,annual,321.45,0.00,active
4,2,katie wilson,data scientist,thompson llc,toronto,netherlands,1979-08-25,2025-05-14,2025-05-23,active,297513.53,SUB-004816,starter,quarterly,45.44,0.20,active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,1499,melissa harvey,product manager,greene solutions,cape town,egypt,1985-03-15,2025-11-01,2025-02-21,active,671214.32,SUB-005487,professional,quarterly,161.69,0.20,active
7002,1499,melissa harvey,product manager,greene solutions,cape town,egypt,1985-03-15,2025-11-01,2025-02-21,active,671214.32,SUB-005556,business,annual,299.79,0.05,expired
7003,1499,melissa harvey,product manager,greene solutions,cape town,egypt,1985-03-15,2025-11-01,2025-02-21,active,671214.32,SUB-005630,enterprise,monthly,904.65,0.10,active
7004,1499,melissa harvey,product manager,greene solutions,cape town,egypt,1985-03-15,2025-11-01,2025-02-21,active,671214.32,SUB-006872,business,annual,300.83,0.10,active
7005,1500,matthew bowen,it specialist,mcbride technologies,madrid,india,1969-07-13,2024-04-16,2025-02-21,inactive,496217.13,SUB-001931,enterprise,quarterly,840.12,0.20,expired

In [ ]:
customer_subscriptions.groupby(["account_status"])

In [140]:
all_data = pd.merge(campaign_interactions , marketing_campaigns , on="campaign_id")
all_data = pd.merge(all_data , customers , on="user_id")
all_data = pd.merge(all_data , subscriptions , on="user_id")
all_data = pd.merge(all_data , support_tickets , on="user_id")
all_data = pd.merge(all_data , all_trans , on="user_id")
all_data

,interaction_id,user_id,campaign_id,interaction_date,interaction_type,campaign_converted,campaign_name,campaign_channel,campaign_type,campaign_budget,...,tic_category,tic_priority,tic_resolution_hours,cus_satisfaction,ticket_status,transaction_id,transaction_date,trans_amount,trans_payment_method,transaction_type
0,INT-0000001,737,CMP-0022,2025-10-15,email open,no,proactive regional workforce,email,retention,42955.00,...,account,high,2.7,3.000000,closed,Q1-TX-000063,2025-01-03,263.31,credit card,add_on
1,INT-0000001,737,CMP-0022,2025-10-15,email open,no,proactive regional workforce,email,retention,42955.00,...,account,high,2.7,3.000000,closed,Q1-TX-000374,2025-02-15,285.92,bank transfer,upgrade
2,INT-0000001,737,CMP-0022,2025-10-15,email open,no,proactive regional workforce,email,retention,42955.00,...,account,high,2.7,3.000000,closed,Q1-TX-000909,2025-01-14,-233.00,debit card,refund
3,INT-0000001,737,CMP-0022,2025-10-15,email open,no,proactive regional workforce,email,retention,42955.00,...,account,high,2.7,3.000000,closed,Q2-TX-000572,2025-05-28,205.00,bank transfer,subscription
4,INT-0000001,737,CMP-0022,2025-10-15,email open,no,proactive regional workforce,email,retention,42955.00,...,account,high,2.7,3.000000,closed,Q2-TX-002804,2025-04-26,-230.11,bank transfer,refund
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2157947,INT-0015000,984,CMP-0003,2025-03-25,demo request,no,organic clear-thinking product,linkedin,upsell,8895.16,...,account,medium,13.4,2.976602,closed,Q1-TX-001953,2025-03-02,89.00,debit card,add_on
2157948,INT-0015000,984,CMP-0003,2025-03-25,demo request,no,organic clear-thinking product,linkedin,upsell,8895.16,...,account,medium,13.4,2.976602,closed,Q2-TX-002290,2025-06-03,107.60,credit card,subscription
2157949,INT-0015000,984,CMP-0003,2025-03-25,demo request,no,organic clear-thinking product,linkedin,upsell,8895.16,...,account,medium,13.4,2.976602,closed,Q2-TX-002835,2025-04-02,206.06,debit card,upgrade
2157950,INT-0015000,984,CMP-0003,2025-03-25,demo request,no,organic clear-thinking product,linkedin,upsell,8895.16,...,account,medium,13.4,2.976602,closed,Q3-TX-000735,2025-08-24,147.08,credit card,subscription
2157951,INT-0015000,984,CMP-0003,2025-03-25,demo request,no,organic clear-thinking product,linkedin,upsell,8895.16,...,account,medium,13.4,2.976602,closed,Q3-TX-001946,2025-08-13,-263.83,debit card,refund

In [142]:
all_data.groupby("full_name")["interaction_id"].count().reset_index().sort_values(by="full_name" , ascending= True).head(5)

       full_name  interaction_id
0     aaron bray            2200
1   aaron duarte             720
2  aaron francis            2464
3     aaron king             400
4   aaron lawson             840